# Server配置 (服务器启动配置)
httpPort: 80

mysql:
  host: 123.207.15.235
  user: root
  password: Sonamu14mysqL
  database: blogs

redis:
  host: 123.207.15.235
  port: 6379
  db: 0

mail: 
  service: qq
  auth:
    user: admin@sonamu.cn
    pass: bntkdjqcdccuebhi

# APP配置 (项目内部配置)
static: # 静态资源文件路径 以/结尾
  styles: http://localhost/styles/
  scripts: http://localhost/scripts/
  images: http://localhost/images/
  plugins: http://localhost/plugins/
  avatar: avatar.png
