# Server配置 (服务器启动配置)
httpPort: 80
mongoUrl: mongodb://localhost:27017/test

mail: 
  service: qq
  auth:
    user: admin@sonamu.cn
    pass: bntkdjqcdccuebhi

# APP配置 (项目内部配置)
static: # 静态资源文件路径 以/结尾
  css: http://localhost/
  js: http://localhost/
  images: http://localhost/
  avatar: images/avatar.png
